# supabase/config.toml
# Configuration for Supabase CLI
[project]
id = "rhuzpwmnzbpnmkbsjtpp"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"

[studio]
enabled = true
port = 54323

[auth]
enable_signup = true
enable_login = true

[auth.external.email]
enabled = true
enable_confirmations = true

[storage]
enabled = true
